images:
- source: ghcr.io/pocket-id/pocket-id
  destination: quay.io/tjarbo/pocket-id
  tags:
  - v2
- source: lscr.io/linuxserver/code-server
  destination: quay.io/tjarbo/code-server
  tags:
  - latest
